---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: springcloud/pipeline-base
inputs:
  - name: repo
  - name: version
  - name: m2
outputs:
  - name: out
run:
  path: /bin/bash
  args:
    - repo/ci/tasks/test-integration.sh
